### ISSUE TITLE
Add title and metadata to trial object

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#103]
Thinking about how we can generate good data from our experiments, I think we need a few more field in the trial object. Here's what we have right now.  

```
 "dotplot-low": {
          // The description is used in the admin panel and not shown to particpants. 
          "description": "Task 1: low temperatures.",
          "instruction": '''
```

Here's what we should have: 

```
 "dotplot-low": {
          // The description is used in the admin panel and not shown to particpants. 
          "title": "T1-low-temp"
          "properties": [
               temp: low,
               difficulty: 1,
               nr-dots: 18
          }
          "description": "Task 1: low temperatures.",
          "instruction": '''
```

The content of properties is a flat array of key-value pairs. These will then be mapped to observations in tidy data.

**Comment by kirangadhave** [comment]
@dyr429 do we have any progress or plans on adding metadata to trials? I will implement tidy download but before that we should fix the top level key we will use for trial metadata.

**Comment by dyr429** [comment]
Yes, I'm working on it. Should have it ready this afternoon

**Comment by kirangadhave** [comment]
cool
