### ISSUE TITLE
Survey study is completely broken

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#114]
Just shows an empty page.

**Comment by alexsb** [comment]
This still shows nothing on the deployed page: 



![Image](https://github.com/revisit-studies/study/assets/2039375/fe17a219-0e9a-482d-b2f2-75c4ef7076e2)

**Comment by JackWilb** [comment]
I see this is working on the deployed version
<img width="1624" alt="Screenshot 2023-05-15 at 2 22 29 PM" src="https://github.com/revisit-studies/study/assets/36867477/c4010b32-818d-4360-8c98-19081117cbe2">
