### ISSUE TITLE
Should we allow for 'deep merging' of baseComponents

### ISSUE THREAD

**Issue by ZachCutler04** [revisit-studies/study#175]
Should we allow for 'deep merging' of baseComponents, or is this too confusing for the user? for example, if the baseComponent has a parameters 

{
 data: [a, b, c],
 number: 5
}

and the component using the base has a parameters 

{
 number: 4
}

Should the actual component use the baseComponents data, or should the data field be empty? Automatically using the data field is certainly more powerful, but may be confusing and difficult to debug for a user who does not properly understand what the inheritance is doing.

**Comment by JackWilb** [comment]
Yes and we do
