### ISSUE TITLE
Fix random blank line in Tidy CSV download

### ISSUE THREAD

**Issue by codementum** [revisit-studies/study#208]
**Describe the bug**
Tidy CSV downloads can result in random blank lines

**To Reproduce**
Happens occasionally with Tidy Download (see screenshot)

**Expected behavior**
There should be no blank lines in the tidy CSV download

**Screenshots**
<img width="1436" alt="image" src="https://github.com/revisit-studies/study/assets/412089/d3471a63-55af-45c9-af0e-2676575143ba">

**Comment by JackWilb** [comment]
I'm going to close this as fixed in #220. Let's reopen or open another issue if it's not resolved
