### ISSUE TITLE
Do we add `name` field for each task in the config?

### ISSUE THREAD

**Issue by hilsonshrestha** [revisit-studies/study#234]
Currently the config does not have a field `name`, and we are using `key` for the sidebar.
Should we instead have a separate field like `name` in the config for each stimuli?

![image](https://github.com/revisit-studies/study/assets/3049313/0dddac10-4619-4637-95d8-14d1ff49824d)

**Comment by JackWilb** [comment]
I think key is better for individual components, but groups might benefit from an identifier
