### ISSUE TITLE
Moving config to firebase storage

### ISSUE THREAD

**Issue by dyr429** [revisit-studies/study#266]
**Is your feature request related to a problem? Please describe.**
The config file is currently stored in the cloud fire store, when the config file exceeds the max allowed 1,048,576 bytes, it throws error.

**Describe the solution you'd like**
Moving config file to storage, like sequences.

**Additional context**
This error happens when we are developing an experiment that has 1400 questions.

**Comment by JackWilb** [comment]
Prefix storage folders with dev- or prod-

**Comment by JackWilb** [comment]
Closed via #387
