### ISSUE TITLE
Changes to the config should be reflected without clearing cache

### ISSUE THREAD

**Issue by bbollen23** [revisit-studies/study#271]
**Is your feature request related to a problem? Please describe.**
Cache must be cleared before changes in the configuration file can be seen by a user, even if the configuration file is invalid.

**Describe the solution you'd like**
Possibly only re-use an old configuration if the user has completed the task successfully. This would prevent having to clear your cache when the configuration is not working or if you are in the testing phase of designing the study. Optionally, entering the study in Admin mode would not trigger any data being cached. This way, the Admin mode would serve as both an Admin and Developer mode of some sort.

**Comment by JackWilb** [comment]
This should probably only apply in the admin mode, since the participants shouldn't have a changed config if they return to the study

**Comment by bbollen23** [comment]
Agreed. Edited the original request to reflect this.

**Comment by JackWilb** [comment]
Closed via #312
