### ISSUE TITLE
Introduce two modes in Study Browser

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#319]
Mode 1 is the **Study Overview**
* this is the default
* it shows the blocks and tasks as listed in the config
* randomization is visible / listed but *not* applied

Mode 2 is the **Participant Simulator**
* this is basically what we have now
* here randomization is applied, skipped elements are grayed out and can't be "visited"
* At the top there is a "next" and "previous" participant dial

**Comment by JackWilb** [comment]
Closed via #389
