### ISSUE TITLE
Better error messages when asset not found

### ISSUE THREAD

**Issue by codementum** [revisit-studies/study#327]
**Describe the bug**
In the Tutorial, I did not put the `introduction.md` in the assets folder. 
The error message I got wasn't all that helpful -> 
<img width="1283" alt="image" src="https://github.com/revisit-studies/study/assets/412089/11951154-281d-40ca-b001-44ec5314c0e0">

**To Reproduce**
1. Leave `introduction.md` out of assets folder
2. Go to localhost:8080 and click the study

**Expected behavior**
I would expect that somehow it says "introduction.md not found. Is this file available and in the right place?"

**Screenshots**
above

**Additional context**
n/a

**Comment by JackWilb** [comment]
Closed via #385
