### ISSUE TITLE
Replace next participant icon

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#392]
Right now this uses the same study browser icon: 

<img width="288" alt="image" src="https://github.com/revisit-studies/study/assets/2039375/78b5ea69-bb30-41c4-a17b-7f2715420ccc">

Probably this one will work

<img width="690" alt="image" src="https://github.com/revisit-studies/study/assets/2039375/8ceb5d35-95de-4c08-a50a-9f9962783bf6">

Or this one 

<img width="696" alt="image" src="https://github.com/revisit-studies/study/assets/2039375/d05c0107-b6f5-4be3-90c5-929bd487c04d">

**Comment by JackWilb** [comment]
Closed via https://github.com/revisit-studies/study/commit/f16bd78aa43d9d10fe843e65a09435a1f8338c41
