### ISSUE TITLE
Improve "Participant View" toggle

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#397]
I think it would be good to have an explicit state that's not the "Participant View". We could call it "All Items View" or "Browsing View". 

If this looks odd with the toggle, should we consider tabs?

Add a question mark icon that provides help text on tool-tip (like in UpSet). 

Text: "The All Items View shows all items in the order defined in the config." "The Participants View shows items just as a participants would see them, considering randomizations, omissions, etc. You can navigate between multiple participants."

**Comment by JackWilb** [comment]
Closed via #401
