### ISSUE TITLE
Studies page: allow command/ctrl click to open in multiple tabs

### ISSUE THREAD

**Issue by codementum** [revisit-studies/study#424]
**Is your feature request related to a problem? Please describe.**

On the main studies page, I often find myself wanting to open a study but also leaving that page open (e.g. to getting to the analysis dashboard or code). 

**Describe the solution you'd like**
It would be great to be able to option or command click to open in a new tab. 
Or just have them open in a new tab :)

**Describe alternatives you've considered**
I can't seem to get it to do the behavior otherwise.

One option might be an explicit clickable link?

**Additional context**
n/a

**Comment by JackWilb** [comment]
Closed via #428
