### ISSUE TITLE
Page titles for analytics, main page, individual studies

### ISSUE THREAD

**Issue by codementum** [revisit-studies/study#425]
**Is your feature request related to a problem? Please describe.**
I'm finding that the multiple tabs that say "reVISit" only make it difficult to know what tab I'm going to when debugging or showing studies. 

**Describe the solution you'd like**
Some simple field for study pages, and something embedded for pages we can't change, like the analytics page. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by JackWilb** [comment]
Closed via #428
