### ISSUE TITLE
Answers can be presented in "RED" color if the participant clicks on "check answer"

### ISSUE THREAD

**Issue by elizaan** [revisit-studies/study#436]
**Is your feature request related to a problem? Please describe.**
If I click on check answer, it shows the correct answers in black which is not easily noticeable

**Describe the solution you'd like**
I would prefer the answers to be presented in red color

**Describe alternatives you've considered**

**Additional context**
Adding a picture of how it currently looks
<img width="434" alt="Screenshot 2024-07-22 at 1 48 20 PM" src="https://github.com/user-attachments/assets/aa832d80-0892-463f-9007-d93f46b535ef">

**Comment by JackWilb** [comment]
Closed via #428
