### ISSUE TITLE
Possible Slider Bug

### ISSUE THREAD

**Issue by bbollen23** [revisit-studies/study#495]
**Describe the bug**
Slider documentation gives example of slider with strings as the options. Only allows for number interface.

**To Reproduce**
1. Config to reproduce is attached.
[config.json](https://github.com/user-attachments/files/17925637/config.json)

**Expected behavior**
Documentation should either be fixed or Slider should allow string inputs.
https://revisit.dev/docs/typedoc/interfaces/SliderResponse/

@JackWilb Thoughts?

**Comment by JackWilb** [comment]
The bug was in the docs. Fixed with the latest release
