### ISSUE TITLE
Iframe in mvnv is still? cut off

### ISSUE THREAD

**Issue by alexsb** [revisit-studies/study#96]
![Image](https://user-images.githubusercontent.com/2039375/236355919-ba50ba54-fb79-4306-99d0-ee1aaed5d823.png)

**Comment by hilsonshrestha** [comment]
This was already fixed in #72 .

**Comment by alexsb** [comment]
OK, but it's not in the live version?

**Comment by hilsonshrestha** [comment]
It is in the live version.

**Comment by alexsb** [comment]
No :) 

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/2039375/236535125-71a86ab8-0494-4cc7-bb07-d37cc3559fe6.png">

**Comment by alexsb** [comment]
I should say it sometimes work, but other times doesn't. I cleared my cache and local storage.

**Comment by hilsonshrestha** [comment]
@dyr429 Can you confirm if MVNV study is completely loaded when this runs:

https://github.com/revisit-studies/study/blob/660c4eb827cf5c62e7337b4cdac62067f243aade/public/html-stimuli/mvnv-study/js/generateTwitterGraph.js#L287-L289

If not, could you remove this and call 
`Revisit.postReady(); `  when the study is completely loaded and rendered?

**Comment by dyr429** [comment]
Yeah, it is. It works on my end.
